version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.6-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3

    steps:
      - checkout

      - restore_cache:
          keys:
            - rails-vendor-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle check || bundle install --path=vendor/bundle
      - save_cache:
          key: rails-vendor-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup DB
          command: bundle exec rake db:create db:migrate

      - run:
          name: Run rspec in parallel
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      - store_test_results:
          path: test_results

  lint:
    docker:
      - image: circleci/ruby:2.6-node-browsers

    steps:
      - checkout

      - run:
          name: Install Pronto
          command: sudo apt-get update && sudo apt-get -y install cmake && gem install pronto pronto-rubocop

      - run:
          name: Execute Pronto
          command: |
            export GITHUB_API_ENDPOINT=$(echo $CI_PULL_REQUEST | sed -e 's/github.com/api.github.com\/repos/g' | sed -e 's/pull/pulls/')
            export BASE_COMMIT=$(curl --silent -H "Authorization: token $PRONTO_GITHUB_ACCESS_TOKEN" $GITHUB_API_ENDPOINT | jq -r .base.sha)
            pronto run \
              --runner=rubocop --formatters github_pr_review --commit=$BASE_COMMIT --exit-code

workflows:
  version: 2
  test:
    jobs:
      - rspec
      - lint